### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by LachlanMcKee** [queueit/android-webui-sdk#17]
Would it be possible to migrate to the AndroidX libraries?

I am hoping to turn off the Jetifier tool (as this is blocking us from updating other tooling) and this is the only library in my project that still uses the support libraries.

**Comment by sp0x** [comment]
A new package is now available that uses the AndroidX libraries.
To add it you should just use this dependency.
`implementation 'com.queue_it.androidsdk:library-androidx:2.0.25'`
If gradle doesn't find that, just add this in your repositories
```
maven {
	url  "https://dl.bintray.com/queueit/maven"
}
```
