### ISSUE TITLE
i can't use library for androidx.

### ISSUE THREAD

**Issue by jc7003** [queueit/android-webui-sdk#18]
I follow sample use `implementation 'com.queue_it.androidsdk:library-androidx:2.0.25'` for include sdk

The Android Studio error report:

![截圖 2020-12-10 下午3 45 40](https://user-images.githubusercontent.com/1667774/101736681-c23fd700-3afe-11eb-8ab6-fb1940c78df2.png)

I can find queue-it SDK library for androidx

**Comment by sp0x** [comment]
You may need to add the maven repository, like this:

```
repositories {
	maven {
		url  "https://dl.bintray.com/queueit/maven"
	}
}
```

**Comment by jc7003** [comment]
Thanks you,  i can use sdk of androidx.
