### ISSUE TITLE
Bintray to be dismissed - migrate to Maven Central

### ISSUE THREAD

**Issue by sameerjj** [queueit/android-webui-sdk#19]
Bintray is scheduled to be dismissed on May 1st, 2021, and no more submissions will be accepted starting from February 28th.  
Realm should be migrated to Maven Central as soon as possible.  
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by sp0x** [comment]
We have migrated to maven central.
The group name has changed to com.queue-it.androidsdk
