### ISSUE TITLE
Strict requirement for Activity context seems unnecessary

### ISSUE THREAD

**Issue by shekibobo** [queueit/android-webui-sdk#20]
There is a constructor for `QueueITEngine` that has a parameter `Activity applicationContext`, which is misleading in its name, and seems like an unnecessary type restriction. The only places I saw in the code that the context is used is for fetching various resources and system services. This restriction to `Activity` contexts prevents one from running a queue in a global context from the Application class. Is there a reason for restricting the type to `Activity`? It seems like there was an issue a few years ago where it was changed to the more generic `Context`, but was then changed back in 5a3262ed633535404e6a34a4a462efb831abb998 without renaming it from `applicationContext`.

**Comment by sp0x** [comment]
The change was made because we use the context to start a new activity.
If you have a context that's an application context this will be problematic.
Can you get the current activity for the context and use that to make the call?

**Comment by shekibobo** [comment]
I'm unclear on how using the application context is problematic for launching an activity. Is it to ensure the queue activity has an activity to fall back to when it finishes?

**Comment by sp0x** [comment]
[This](https://web.archive.org/web/20150329210012/https://possiblemobile.com/2013/06/context/) blog post might be helpful. If you're starting an activity from the application context you'll need to start a new task and configure your manifest for that.
That's not recommended and it's not good practice
