### ISSUE TITLE
onQueuePassed does not return a queueit token

### ISSUE THREAD

**Issue by shinjikanai** [queueit/android-webui-sdk#30]
Please document clearly to ensure that the connector token type in the waiting room settings is set to v3 or higher, not JavaScript. The mobile SDK searches for the 'queueittoken' parameter to extract the token value. However, if JavaScript is used, the 'qitq' parameter conveys the value, leading to issues with the token retrieval process.

**Comment by Hesi01** [comment]
Hi shinji

can you suggest the text, and send it to me. 

kind regards 

Herprit
